version: '3'
services:

  general:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROS_DOMAIN_ID=8
      - ROS_MASTER_URI=http://ros1-core:11311
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
      - /home/frankvp11/Documents/Simulation:/home
    stdin_open: true
    tty: true
    privileged: true
    command: /./simulation_entrypoint.sh

  health_display3:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROS_DOMAIN_ID=8
      - ROS_MASTER_URI=http://ros1-core:11311
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    stdin_open: true
    tty: true
    privileged: true
    command: /./rviz2_entrypoint.sh
    
  state_publisher:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - ROS_DOMAIN_ID=8
      - ROS_MASTER_URI=http://ros1-core:11311
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    stdin_open: true
    tty: true
    privileged: true
    command: /./health_pub_entrypoint.sh
  
  rl_stuff:
    build:
      context: .
      dockerfile: torchDockerfile
    environment:
      - ROS_DOMAIN_ID=8
      - ROS_MASTER_URI=http://ros1-core:11311
      - DISPLAY=:0
      - QT_X11_NO_MITSHM=1
      - QT_QPA_PLATFORM=xcb
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - $HOME/.Xauthority:/root/.Xauthority:rw
    stdin_open: true
    tty: true
    privileged: true
    command: /./rl_entrypoint.sh